### ISSUE TITLE
MSPT increases from 21 to 0ver 40

### ISSUE THREAD

**Issue by sha-doh** [Pretorer/LiftMechanics#1]
Im using v 1.0 on paper (purpur) 1.19.4 and when i enable this datapack my server mspt goes from 20-40 instantly upon enabling! ive disabled all other datapacks and determined this one to be the bad actor.. is there anything in paper(purpur) that could be causing this?

**Comment by Pretorer** [comment]
I'm sorry for replying so late. 
I tried to repoduce this bahvior on vanilla and on a paper server, but I could not observe such a strong impact on performance. In the past I have reduced the static load a bit by using advancements.
